### ISSUE TITLE
GitLab CI

### ISSUE THREAD

**Issue by Krypton-Nova** [AlexDarigan/WAT-Mono#26]
Personally I spent way to long figuring out how to create a working gitlab-ci setup (before finally realising GitHub actions are really similar, anyway). Maybe it's a good idea to include a .gitlab-ci.yml example?

This is what's currently working for me:
```
image: barichello/godot-ci:mono-3.3.1

stages:
  - test

wat-sharp:
  stage: test
  script:
    - nuget restore
    - mkdir -p .mono/assemblies/Debug
    - cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug
    - msbuild
    - godot addons/WAT/cli.tscn -run_all
```
